// apps/mvc-blueprint-03/src/ui/sys/action/action-button.tsx
import { Button } from "@statewalker/ui.view.shadcn";
import type { ActionView } from "@sys/action/model";
import { useModel } from "@ui/host";
import type { ComponentProps } from "react";

export interface ActionButtonProps {
  readonly action: ActionView;
  readonly variant?: ComponentProps<typeof Button>["variant"];
  readonly size?: ComponentProps<typeof Button>["size"];
  readonly className?: string;
  readonly ariaLabel?: string;
}

/** Any action as a button: its label, icon and hint; disabled while not enabled or running. */
export function ActionButton({ action, variant, size, className, ariaLabel }: ActionButtonProps) {
  const state = useModel(action.getState, action.onStateUpdate);
  return (
    <Button
      type="button"
      variant={variant}
      size={size}
      className={className}
      aria-label={ariaLabel}
      aria-busy={state.running}
      data-icon={state.icon}
      title={state.hint}
      disabled={!state.enabled || state.running}
      onClick={() => action.submit()}
    >
      {state.label}
    </Button>
  );
}

// apps/mvc-blueprint-08/src/kits/svelte/ActionButton.svelte
<script lang="ts">
import type { ActionView } from "@kernel";
import { modelStore } from "./store.js";

/** Any action as a button: label, hint; disabled while not enabled or running. */
let { action, class: className }: { action: ActionView; class?: string } = $props();
const s = $derived(modelStore(action.getState, action.onStateUpdate));
</script>

<button
  type="button"
  class={className ?? "rounded border px-3 py-1 text-sm disabled:opacity-50"}
  title={$s.hint}
  aria-busy={$s.running}
  disabled={!$s.enabled || $s.running}
  onclick={() => action.submit()}
>{$s.label}</button>
