// apps/mvc-blueprint-04/src/bundles/todos.ui.react/index.ts
import { type ReactRenderer, reactRenderersSlot } from "@b/shell/api/react";
import { clearCompletedKind, todoEditorKind, todoListKind, todoRenameKind } from "@b/todos/api";
import { type Controller, getSlots, newRegistry, type ViewKind } from "@kernel";
import type { ComponentType } from "react";
import { ClearCompletedDialog, TodoEditor, TodoList } from "./views.js";

/** `todos.ui.react`: contributes the Todos renderers for React. Wiring only. */
export const activate: Controller = async (context) => {
  const slots = getSlots(context);
  const [register, cleanup] = newRegistry();
  const add = <M>(kind: ViewKind<M>, component: ComponentType<{ model: M }>) =>
    register(
      slots.register(reactRenderersSlot, kind.id, {
        kind,
        component,
      } satisfies ReactRenderer<M> as unknown as ReactRenderer<never>),
    );
  add(todoListKind, TodoList);
  add(todoEditorKind, TodoEditor);
  add(todoRenameKind, TodoEditor);
  add(clearCompletedKind, ClearCompletedDialog);
  return cleanup;
};

// apps/mvc-blueprint-08/src/bundles/todos.ui.solid/index.ts
import { type SolidRenderer, solidRenderersSlot } from "@b/shell/api/solid";
import { clearCompletedKind, todoEditorKind, todoListKind, todoRenameKind } from "@b/todos/api";
import { type Controller, getSlots, newRegistry, type ViewKind } from "@kernel";
import type { Component } from "solid-js";
import { ClearCompletedDialog, TodoEditor, TodoList } from "./views.js";

/** `todos.ui.solid`: contributes the Todos renderers for Solid. Wiring only. */
export const activate: Controller = async (context) => {
  const slots = getSlots(context);
  const [register, cleanup] = newRegistry();
  const add = <M>(kind: ViewKind<M>, component: Component<{ model: M }>) =>
    register(
      slots.register(solidRenderersSlot, kind.id, {
        kind,
        component,
      } satisfies SolidRenderer<M> as unknown as SolidRenderer<never>),
    );
  add(todoListKind, TodoList);
  add(todoEditorKind, TodoEditor);
  add(todoRenameKind, TodoEditor);
  add(clearCompletedKind, ClearCompletedDialog);
  return cleanup;
};
