// apps/mvc-blueprint-08/src/kits/svelte/ActionButton.svelte
<script lang="ts">
import type { ActionView } from "@kernel";
import { modelStore } from "./store.js";

/** Any action as a button: label, hint; disabled while not enabled or running. */
let { action, class: className }: { action: ActionView; class?: string } = $props();
const s = $derived(modelStore(action.getState, action.onStateUpdate));
</script>

<button
  type="button"
  class={className ?? "rounded border px-3 py-1 text-sm disabled:opacity-50"}
  title={$s.hint}
  aria-busy={$s.running}
  disabled={!$s.enabled || $s.running}
  onclick={() => action.submit()}
>{$s.label}</button>

// apps/mvc-blueprint-07/src/kit/react/action-button.tsx
import type { ActionView } from "../../kernel/models.js";
import { useModel } from "./use-model.js";

/** Renders an ActionView: label, enabled, running. A click is the action's `submit()`. */
export function ActionButton({ action, role }: { action: ActionView; role?: string }) {
  const state = useModel(action.getState, action.onStateUpdate);
  return (
    <button
      type="button"
      role={role}
      disabled={!state.enabled || state.running}
      aria-busy={state.running || undefined}
      title={state.hint}
      onClick={() => action.submit()}
    >
      {state.label}
    </button>
  );
}
